name: C CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v6
      - name: Build application
        run: CC=${{ matrix.compiler }} sh scripts/build.sh
      - name: Run tests
        run: CC=${{ matrix.compiler }} sh scripts/test.sh
